### ISSUE TITLE
Find a way to hide the bot token

### ISSUE THREAD

**Issue by louis-mudrack** [louis-mudrack/codibot#3]
Really important or i get spammed by discord every commit

**Comment by Tim-Raphael** [comment]
Just use an environment variable. You could start here if you need more information. - [https://docs.w3cub.com/cpp/utility/program/getenv](https://docs.w3cub.com/ccpppp/utility/program/getenv)

**Comment by louis-mudrack** [comment]
was my first idea but didnt really look into that at the moment. will do
